### PR TITLE
Demo_v2.0 : Tag_v1.1 : Coding Final

### PR DESCRIPTION
**Pull request by BeautifulMoon211**

### CODE REVIEW

**Review by BeautifulMoon211 — COMMENTED** [review]
Finish coding.
Finish video demo.
Finish Tag_v1.1.

**Review by HighAmbition211 — COMMENTED** [review]
Yeah, quite good.
Just prepare a good README.md.
It will be a fabulous one.

**Comment by HighAmbition211** [comment]
Hey, don't forget to add an example file to tag_v1.1

**Comment by BeautifulMoon211** [comment]
You do.

**Comment by HighAmbition211** [comment]
😤

**Pull request merged**
